# Generated by Django 3.2.12 on 2022-08-17 06:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('soft_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
