# Generated by Django 3.2.7 on 2022-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220826_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
